### ISSUE TITLE
Doesn't format dialogues 

### ISSUE THREAD

**Issue by Luggruff** [polevaultweb/DeLorean-Ipsum#2]
It's pretty weird reading the paragraphs as it reads as a schizophrenic or something not being formatted as a dialogue. Something to consider perhaps.

**Comment by jazzsequence** [comment]
Formatting as dialogs would sort of defeat the purpose of using it as filler text, e.g. an alternative to [lorem ipsum](https://loremipsum.io/). It would no longer appear, at a glance, as normal paragraph content because of the formatting.

**Comment by polevaultweb** [comment]
Indeed, what @jazzsequence said.
